[target.x86_64-pc-windows-msvc]
rustflags = ["-Clink-arg=advapi32.lib", "-Clink-arg=crypt32.lib"]

[target.i686-pc-windows-msvc]
rustflags = ["-Clink-arg=advapi32.lib", "-Clink-arg=crypt32.lib"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-Clink-arg=advapi32.lib", "-Clink-arg=crypt32.lib"]
